// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.0
// source: pkg/proto/revocation/revocation.proto

package revocation

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetProofRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"` // hex string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofRequest) Reset() {
	*x = GetProofRequest{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofRequest) ProtoMessage() {}

func (x *GetProofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofRequest.ProtoReflect.Descriptor instead.
func (*GetProofRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{0}
}

func (x *GetProofRequest) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *GetProofRequest) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type GetProofResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IssuerId      string                 `protobuf:"bytes,1,opt,name=issuer_id,json=issuerId,proto3" json:"issuer_id,omitempty"`
	SerialNumber  string                 `protobuf:"bytes,2,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
	Entry         []string               `protobuf:"bytes,3,rep,name=entry,proto3" json:"entry,omitempty"`
	MatchingEntry []string               `protobuf:"bytes,4,rep,name=matching_entry,json=matchingEntry,proto3" json:"matching_entry,omitempty"`
	Siblings      []string               `protobuf:"bytes,5,rep,name=siblings,proto3" json:"siblings,omitempty"`
	Root          string                 `protobuf:"bytes,6,opt,name=root,proto3" json:"root,omitempty"`
	Membership    bool                   `protobuf:"varint,7,opt,name=membership,proto3" json:"membership,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProofResponse) Reset() {
	*x = GetProofResponse{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProofResponse) ProtoMessage() {}

func (x *GetProofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProofResponse.ProtoReflect.Descriptor instead.
func (*GetProofResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{1}
}

func (x *GetProofResponse) GetIssuerId() string {
	if x != nil {
		return x.IssuerId
	}
	return ""
}

func (x *GetProofResponse) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

func (x *GetProofResponse) GetEntry() []string {
	if x != nil {
		return x.Entry
	}
	return nil
}

func (x *GetProofResponse) GetMatchingEntry() []string {
	if x != nil {
		return x.MatchingEntry
	}
	return nil
}

func (x *GetProofResponse) GetSiblings() []string {
	if x != nil {
		return x.Siblings
	}
	return nil
}

func (x *GetProofResponse) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *GetProofResponse) GetMembership() bool {
	if x != nil {
		return x.Membership
	}
	return false
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{2}
}

type GetStatusResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Generations   map[string]*IssuerStatus `protobuf:"bytes,1,rep,name=generations,proto3" json:"generations,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UptimeSeconds float64                  `protobuf:"fixed64,2,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{3}
}

func (x *GetStatusResponse) GetGenerations() map[string]*IssuerStatus {
	if x != nil {
		return x.Generations
	}
	return nil
}

func (x *GetStatusResponse) GetUptimeSeconds() float64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type IssuerStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Loaded        bool                   `protobuf:"varint,1,opt,name=loaded,proto3" json:"loaded,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Root          string                 `protobuf:"bytes,3,opt,name=root,proto3" json:"root,omitempty"`
	CrlNumber     uint64                 `protobuf:"varint,4,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	LoadedAt      string                 `protobuf:"bytes,5,opt,name=loaded_at,json=loadedAt,proto3" json:"loaded_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuerStatus) Reset() {
	*x = IssuerStatus{}
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuerStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuerStatus) ProtoMessage() {}

func (x *IssuerStatus) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_revocation_revocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuerStatus.ProtoReflect.Descriptor instead.
func (*IssuerStatus) Descriptor() ([]byte, []int) {
	return file_pkg_proto_revocation_revocation_proto_rawDescGZIP(), []int{4}
}

func (x *IssuerStatus) GetLoaded() bool {
	if x != nil {
		return x.Loaded
	}
	return false
}

func (x *IssuerStatus) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *IssuerStatus) GetRoot() string {
	if x != nil {
		return x.Root
	}
	return ""
}

func (x *IssuerStatus) GetCrlNumber() uint64 {
	if x != nil {
		return x.CrlNumber
	}
	return 0
}

func (x *IssuerStatus) GetLoadedAt() string {
	if x != nil {
		return x.LoadedAt
	}
	return ""
}

var File_pkg_proto_revocation_revocation_proto protoreflect.FileDescriptor

const file_pkg_proto_revocation_revocation_proto_rawDesc = "" +
	"\n" +
	"%pkg/proto/revocation/revocation.proto\x12\n" +
	"revocation\"S\n" +
	"\x0fGetProofRequest\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\"\xe1\x01\n" +
	"\x10GetProofResponse\x12\x1b\n" +
	"\tissuer_id\x18\x01 \x01(\tR\bissuerId\x12#\n" +
	"\rserial_number\x18\x02 \x01(\tR\fserialNumber\x12\x14\n" +
	"\x05entry\x18\x03 \x03(\tR\x05entry\x12%\n" +
	"\x0ematching_entry\x18\x04 \x03(\tR\rmatchingEntry\x12\x1a\n" +
	"\bsiblings\x18\x05 \x03(\tR\bsiblings\x12\x12\n" +
	"\x04root\x18\x06 \x01(\tR\x04root\x12\x1e\n" +
	"\n" +
	"membership\x18\a \x01(\bR\n" +
	"membership\"\x12\n" +
	"\x10GetStatusRequest\"\xe6\x01\n" +
	"\x11GetStatusResponse\x12P\n" +
	"\vgenerations\x18\x01 \x03(\v2..revocation.GetStatusResponse.GenerationsEntryR\vgenerations\x12%\n" +
	"\x0euptime_seconds\x18\x02 \x01(\x01R\ruptimeSeconds\x1aX\n" +
	"\x10GenerationsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x05value\x18\x02 \x01(\v2\x18.revocation.IssuerStatusR\x05value:\x028\x01\"\x8c\x01\n" +
	"\fIssuerStatus\x12\x16\n" +
	"\x06loaded\x18\x01 \x01(\bR\x06loaded\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\x12\x12\n" +
	"\x04root\x18\x03 \x01(\tR\x04root\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x04 \x01(\x04R\tcrlNumber\x12\x1b\n" +
	"\tloaded_at\x18\x05 \x01(\tR\bloadedAt2\xa9\x01\n" +
	"\x16RevocationProofService\x12E\n" +
	"\bGetProof\x12\x1b.revocation.GetProofRequest\x1a\x1c.revocation.GetProofResponse\x12H\n" +
	"\tGetStatus\x12\x1c.revocation.GetStatusRequest\x1a\x1d.revocation.GetStatusResponseBGZEgithub.com/moven0831/moica-revocation-smt/server/pkg/proto/revocationb\x06proto3"

var (
	file_pkg_proto_revocation_revocation_proto_rawDescOnce sync.Once
	file_pkg_proto_revocation_revocation_proto_rawDescData []byte
)

func file_pkg_proto_revocation_revocation_proto_rawDescGZIP() []byte {
	file_pkg_proto_revocation_revocation_proto_rawDescOnce.Do(func() {
		file_pkg_proto_revocation_revocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_revocation_revocation_proto_rawDesc), len(file_pkg_proto_revocation_revocation_proto_rawDesc)))
	})
	return file_pkg_proto_revocation_revocation_proto_rawDescData
}

var file_pkg_proto_revocation_revocation_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_proto_revocation_revocation_proto_goTypes = []any{
	(*GetProofRequest)(nil),   // 0: revocation.GetProofRequest
	(*GetProofResponse)(nil),  // 1: revocation.GetProofResponse
	(*GetStatusRequest)(nil),  // 2: revocation.GetStatusRequest
	(*GetStatusResponse)(nil), // 3: revocation.GetStatusResponse
	(*IssuerStatus)(nil),      // 4: revocation.IssuerStatus
	nil,                       // 5: revocation.GetStatusResponse.GenerationsEntry
}
var file_pkg_proto_revocation_revocation_proto_depIdxs = []int32{
	5, // 0: revocation.GetStatusResponse.generations:type_name -> revocation.GetStatusResponse.GenerationsEntry
	4, // 1: revocation.GetStatusResponse.GenerationsEntry.value:type_name -> revocation.IssuerStatus
	0, // 2: revocation.RevocationProofService.GetProof:input_type -> revocation.GetProofRequest
	2, // 3: revocation.RevocationProofService.GetStatus:input_type -> revocation.GetStatusRequest
	1, // 4: revocation.RevocationProofService.GetProof:output_type -> revocation.GetProofResponse
	3, // 5: revocation.RevocationProofService.GetStatus:output_type -> revocation.GetStatusResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_proto_revocation_revocation_proto_init() }
func file_pkg_proto_revocation_revocation_proto_init() {
	if File_pkg_proto_revocation_revocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_revocation_revocation_proto_rawDesc), len(file_pkg_proto_revocation_revocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_revocation_revocation_proto_goTypes,
		DependencyIndexes: file_pkg_proto_revocation_revocation_proto_depIdxs,
		MessageInfos:      file_pkg_proto_revocation_revocation_proto_msgTypes,
	}.Build()
	File_pkg_proto_revocation_revocation_proto = out.File
	file_pkg_proto_revocation_revocation_proto_goTypes = nil
	file_pkg_proto_revocation_revocation_proto_depIdxs = nil
}
